// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFQYFia9HYfs13tLcRD4fLUsQwaWUJjXw',
    appId: '1:640078631538:web:26d0a1155be8cc3a31e8eb',
    messagingSenderId: '640078631538',
    projectId: 'toolforall-9228b',
    authDomain: 'toolforall-9228b.firebaseapp.com',
    databaseURL: 'https://toolforall-9228b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'toolforall-9228b.appspot.com',
    measurementId: 'G-V78PGL9WPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtjPfIXklnM-jpppTh78mcOphCUmsfMIc',
    appId: '1:640078631538:android:d11131077249f7f731e8eb',
    messagingSenderId: '640078631538',
    projectId: 'toolforall-9228b',
    databaseURL: 'https://toolforall-9228b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'toolforall-9228b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-O74P9SOcOn63x4hE5mVUErm6KnyrW8',
    appId: '1:640078631538:ios:4dedaece78ea7a6c31e8eb',
    messagingSenderId: '640078631538',
    projectId: 'toolforall-9228b',
    databaseURL: 'https://toolforall-9228b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'toolforall-9228b.appspot.com',
    iosClientId: '640078631538-1vopvg3l3r7lbbbht385q3fgieffo4oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.toolforallGroup08Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw-O74P9SOcOn63x4hE5mVUErm6KnyrW8',
    appId: '1:640078631538:ios:4dedaece78ea7a6c31e8eb',
    messagingSenderId: '640078631538',
    projectId: 'toolforall-9228b',
    databaseURL: 'https://toolforall-9228b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'toolforall-9228b.appspot.com',
    iosClientId: '640078631538-1vopvg3l3r7lbbbht385q3fgieffo4oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.toolforallGroup08Project',
  );
}
